// Auto-generated by bundle_tiles.js — do not edit directly.
// Edit source files in tile_data/*.jsonc and re-run: node bundle_tiles.js

const TILE_DATA = [
  {
    "id": "TileUFOFloor",
    "g": "≡",
    "c": "#324b6e",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileUFOWall",
    "g": "█",
    "c": "#466496",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TilePod",
    "g": "◈",
    "c": "#8246be",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TilePowerSource",
    "g": "⌁",
    "c": "#f0c83c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileAlienTech",
    "g": "⊕",
    "c": "#e64646",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileCryoPipe",
    "g": "╪",
    "c": "#8cc8e6",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileSkylight",
    "g": "⊙",
    "c": "#b4d2f0",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileWreck",
    "g": "▤",
    "c": "#965f3c",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileDish",
    "g": "◗",
    "c": "#aaafb9",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 50
  },
  {
    "id": "TileFuelPump",
    "g": "8",
    "c": "#c83c28",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileDesk",
    "g": "◊",
    "c": "#a07850",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileChair",
    "g": "⊟",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileChairLeft",
    "g": "⅃",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileChairRight",
    "g": "L",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileComputer",
    "g": "⌸",
    "c": "#46b4d2",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileBed",
    "g": "□",
    "c": "#c8c8c8",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileLocker",
    "g": "◫",
    "c": "#8ca0b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileCabinet",
    "g": "⊞",
    "c": "#aa825a",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileConsole",
    "g": "⌸",
    "c": "#46d282",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileObject",
    "g": "•",
    "c": "#aaaaaa",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 50
  },
  {
    "id": "TileStorage",
    "g": "▤",
    "c": "#b48c5a",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileMachinery",
    "g": "⊛",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileGlass",
    "g": ",",
    "c": "#bec8d2",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileDebris",
    "g": "`",
    "c": "#968c82",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileTree",
    "g": "♣",
    "c": "#235a19",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileRock",
    "g": "∩",
    "c": "#827d78",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 70
  },
  {
    "id": "TileBush",
    "g": "†",
    "c": "#2d6423",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 40
  },
  {
    "id": "TileWheat",
    "g": "ψ",
    "c": "#c8b43c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileVine",
    "g": "‡",
    "c": "#328232",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileBamboo",
    "g": "♣",
    "c": "#50963c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 60
  },
  {
    "id": "TileCypressTree",
    "g": "♣",
    "c": "#285532",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileSnowTree",
    "g": "♣",
    "c": "#dcebf5",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileDryBush",
    "g": "*",
    "c": "#aa8c3c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileBoulder",
    "g": "∩",
    "c": "#827d78",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 70
  },
  {
    "id": "TileHayBale",
    "g": "█",
    "c": "#a08c3c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 60
  },
  {
    "id": "TileFloor",
    "g": ".",
    "c": "#5f5a55",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileWall",
    "g": "#",
    "c": "#a09b96",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileDoor",
    "g": "+",
    "c": "#8c6432",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileWindow",
    "g": "⊞",
    "c": "#78aadc",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileGrass",
    "g": "·",
    "c": "#326e28",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TilePavement",
    "g": "░",
    "c": "#787878",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileSand",
    "g": "·",
    "c": "#c8b478",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileSnow",
    "g": "∗",
    "c": "#e6ebf5",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileScree",
    "g": "·",
    "c": "#a09682",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileMud",
    "g": "≋",
    "c": "#6e5032",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 5
  },
  {
    "id": "TileStairs",
    "g": "▒",
    "c": "#6e6964",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileStairsDown",
    "g": "▓",
    "c": "#504b46",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileCliffFace",
    "g": "░",
    "c": "#8c7864",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileAdobe",
    "g": "█",
    "c": "#c88246",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileMetalWall",
    "g": "█",
    "c": "#b4b9c3",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileFence",
    "g": "│",
    "c": "#917850",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 40
  },
  {
    "id": "TileRubble",
    "g": "▒",
    "c": "#78736e",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 20
  },
  {
    "id": "TileContainerRed",
    "g": "█",
    "c": "#b43228",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileContainerBlue",
    "g": "█",
    "c": "#3250b4",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileContainerYellow",
    "g": "█",
    "c": "#c8aa28",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80
  },
  {
    "id": "TileDockCrate",
    "g": "▣",
    "c": "#967850",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileTimber",
    "g": "≡",
    "c": "#966e3c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileStreetlamp",
    "g": "⌖",
    "c": "#dcd278",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileCar",
    "g": "▄",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileCarMid",
    "g": "█",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileCarRight",
    "g": "▄",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileForklift",
    "g": "█",
    "c": "#c8a028",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileForkliftRight",
    "g": "⊏",
    "c": "#c8a028",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileBusEnd",
    "g": "▄",
    "c": "#c8b43c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileBusMid",
    "g": "█",
    "c": "#c8b43c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileHeloBody",
    "g": "█",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileHeloTail",
    "g": "▄",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileHeloNose",
    "g": "▷",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 40
  },
  {
    "id": "TileHeloRotor",
    "g": "+",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileHeloRotorSides",
    "g": "-",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileHeloBodyBack",
    "g": "█",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileHeloRotorBack",
    "g": "x",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileHeloWindow",
    "g": "◣",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 0
  },
  {
    "id": "TileTractorCab",
    "g": "◣",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileTractorBody",
    "g": "█",
    "c": "#b43c28",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30
  },
  {
    "id": "TileTruck",
    "g": "▄",
    "c": "#5a6e46",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80
  },
  {
    "id": "TileWheel",
    "g": "O",
    "c": "#3c3c3c",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileWheelSmall",
    "g": "o",
    "c": "#3c3c3c",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10
  },
  {
    "id": "TileCrawlerLeft",
    "g": "◢",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileCrawlerMid",
    "g": "█",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileCrawlerRight",
    "g": "◣",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50
  },
  {
    "id": "TileCrawlerLeg",
    "g": "^",
    "c": "#6432a0",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 20
  },
  {
    "id": "TileWater",
    "g": "≈",
    "c": "#2850c8",
    "pa": false,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileMarsh",
    "g": "≋",
    "c": "#3c6446",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TileSwampWater",
    "g": "≋",
    "c": "#326450",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 5
  },
  {
    "id": "TileIce",
    "g": "≈",
    "c": "#b4dceb",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0
  },
  {
    "id": "TilePier",
    "g": "═",
    "c": "#8c643c",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 10
  }
];
