// Auto-generated from data/tiles/*.jsonc
const TILE_DATA = [
  {
    "id": "TileUFOFloor",
    "g": "≡",
    "c": "#324b6e",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_UFO_FLOOR"
  },
  {
    "id": "TileUFOWall",
    "g": "█",
    "c": "#466496",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_UFO_WALL"
  },
  {
    "id": "TilePod",
    "g": "◈",
    "c": "#8246be",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_POD"
  },
  {
    "id": "TilePowerSource",
    "g": "⌁",
    "c": "#f0c83c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_POWER_SOURCE"
  },
  {
    "id": "TileAlienTech",
    "g": "⊕",
    "c": "#e64646",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_ALIEN_TECH"
  },
  {
    "id": "TileCryoPipe",
    "g": "╪",
    "c": "#8cc8e6",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CRYO_PIPE"
  },
  {
    "id": "TileSkylight",
    "g": "⊙",
    "c": "#b4d2f0",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_SKYLIGHT"
  },
  {
    "id": "TileWreck",
    "g": "▤",
    "c": "#965f3c",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WRECK"
  },
  {
    "id": "TileDish",
    "g": "◗",
    "c": "#aaafb9",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_DISH"
  },
  {
    "id": "TileFuelPump",
    "g": "8",
    "c": "#c83c28",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 5,
    "no": false,
    "mv": 4,
    "nm": "TILE_FUEL_PUMP"
  },
  {
    "id": "TileDesk",
    "g": "◊",
    "c": "#a07850",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_DESK"
  },
  {
    "id": "TileChair",
    "g": "⊟",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CHAIR"
  },
  {
    "id": "TileChairLeft",
    "g": "▦",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CHAIR"
  },
  {
    "id": "TileChairRight",
    "g": "▦",
    "c": "#96643c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CHAIR"
  },
  {
    "id": "TileComputer",
    "g": "⌸",
    "c": "#46b4d2",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_COMPUTER"
  },
  {
    "id": "TileBed",
    "g": "□",
    "c": "#c8c8c8",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_BED"
  },
  {
    "id": "TileLocker",
    "g": "◫",
    "c": "#8ca0b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_LOCKER"
  },
  {
    "id": "TileCabinet",
    "g": "⊞",
    "c": "#aa825a",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CABINET"
  },
  {
    "id": "TileConsole",
    "g": "⌸",
    "c": "#46d282",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CONSOLE"
  },
  {
    "id": "TileObject",
    "g": "•",
    "c": "#aaaaaa",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_OBJECT"
  },
  {
    "id": "TileStorage",
    "g": "▤",
    "c": "#b48c5a",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_STORAGE"
  },
  {
    "id": "TileMachinery",
    "g": "⊛",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_MACHINERY"
  },
  {
    "id": "TileGlass",
    "g": ",",
    "c": "#bec8d2",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": true,
    "mv": 4,
    "nm": "TILE_GLASS"
  },
  {
    "id": "TileDebris",
    "g": "`",
    "c": "#968c82",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": true,
    "mv": 4,
    "nm": "TILE_DEBRIS"
  },
  {
    "id": "TileTree",
    "g": "♣",
    "c": "#235a19",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 60,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_TREE"
  },
  {
    "id": "TileRock",
    "g": "∩",
    "c": "#827d78",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 70,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_ROCK"
  },
  {
    "id": "TileBush",
    "g": "ʷ",
    "c": "#2d6423",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 40,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 5,
    "nm": "TILE_BUSH"
  },
  {
    "id": "TileBushTall",
    "g": "ʬ",
    "c": "#2d6423",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 55,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 5,
    "nm": "TILE_BUSH"
  },
  {
    "id": "TileWheat",
    "g": "ψ",
    "c": "#c8b43c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 5,
    "nm": "TILE_WHEAT"
  },
  {
    "id": "TileVine",
    "g": "‡",
    "c": "#328232",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 6,
    "nm": "TILE_VINE"
  },
  {
    "id": "TileBamboo",
    "g": "ዘ",
    "c": "#50963c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 60,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_BAMBOO"
  },
  {
    "id": "TileCypressTree",
    "g": "ፕ",
    "c": "#285532",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_CYPRESS_TREE"
  },
  {
    "id": "TileSnowTree",
    "g": "♣",
    "c": "#dcebf5",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_SNOW_TREE"
  },
  {
    "id": "TileDryBush",
    "g": "ʵ",
    "c": "#aa8c3c",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_DRY_BUSH"
  },
  {
    "id": "TileBoulder",
    "g": "∩",
    "c": "#827d78",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 70,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_BOULDER"
  },
  {
    "id": "TileHayBale",
    "g": "ѻ",
    "c": "#a08c3c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 60,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HAY_BALE"
  },
  {
    "id": "TileFloor",
    "g": ".",
    "c": "#5f5a55",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_FLOOR"
  },
  {
    "id": "TileWall",
    "g": "█",
    "c": "#a09b96",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WALL"
  },
  {
    "id": "TileDoor",
    "g": "+",
    "c": "#8c6432",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_DOOR"
  },
  {
    "id": "TileWindow",
    "g": "□",
    "c": "#78aadc",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WINDOW"
  },
  {
    "id": "TileGrass",
    "g": "·",
    "c": "#326e28",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_GRASS"
  },
  {
    "id": "TilePavement",
    "g": "·",
    "c": "#787878",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 3,
    "nm": "TILE_PAVEMENT"
  },
  {
    "id": "TileSand",
    "g": "·",
    "c": "#c8b478",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 6,
    "nm": "TILE_SAND"
  },
  {
    "id": "TileSnow",
    "g": "∗",
    "c": "#e6ebf5",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 5,
    "nm": "TILE_SNOW"
  },
  {
    "id": "TileScree",
    "g": "·",
    "c": "#a09682",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": true,
    "mv": 6,
    "nm": "TILE_SCREE"
  },
  {
    "id": "TileMud",
    "g": "≋",
    "c": "#6e5032",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 5,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 6,
    "nm": "TILE_MUD"
  },
  {
    "id": "TileStairs",
    "g": "▒",
    "c": "#6e6964",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_STAIRS"
  },
  {
    "id": "TileStairsDown",
    "g": "▓",
    "c": "#504b46",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_STAIRS_DOWN"
  },
  {
    "id": "TileCliffFace",
    "g": "░",
    "c": "#8c7864",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CLIFF_FACE"
  },
  {
    "id": "TileAdobe",
    "g": "█",
    "c": "#c88246",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_ADOBE"
  },
  {
    "id": "TileMetalWall",
    "g": "#",
    "c": "#b4b9c3",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_METAL_WALL"
  },
  {
    "id": "TileFence",
    "g": "│",
    "c": "#917850",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_FENCE"
  },
  {
    "id": "TileRubble",
    "g": "▒",
    "c": "#78736e",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_RUBBLE"
  },
  {
    "id": "TileContainerRed",
    "g": "█",
    "c": "#b43228",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CONTAINER"
  },
  {
    "id": "TileContainerBlue",
    "g": "█",
    "c": "#3250b4",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CONTAINER"
  },
  {
    "id": "TileContainerYellow",
    "g": "█",
    "c": "#c8aa28",
    "pa": false,
    "op": true,
    "de": false,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CONTAINER"
  },
  {
    "id": "TileDockCrate",
    "g": "▣",
    "c": "#967850",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_DOCK_CRATE"
  },
  {
    "id": "TileTimber",
    "g": "≡",
    "c": "#966e3c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": true,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_TIMBER"
  },
  {
    "id": "TileStreetlamp",
    "g": "⌖",
    "c": "#dcd278",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_STREETLAMP"
  },
  {
    "id": "TileCar",
    "g": "▄",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CAR"
  },
  {
    "id": "TileCarMid",
    "g": "█",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CAR"
  },
  {
    "id": "TileCarRight",
    "g": "▄",
    "c": "#3264b4",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CAR"
  },
  {
    "id": "TileForklift",
    "g": "█",
    "c": "#c8a028",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_FORKLIFT"
  },
  {
    "id": "TileForkliftRight",
    "g": "⊏",
    "c": "#c8a028",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_FORKLIFT"
  },
  {
    "id": "TileBusEnd",
    "g": "▄",
    "c": "#c8b43c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_BUS"
  },
  {
    "id": "TileBusMid",
    "g": "█",
    "c": "#c8b43c",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_BUS"
  },
  {
    "id": "TileHeloBody",
    "g": "█",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELICOPTER"
  },
  {
    "id": "TileHeloTail",
    "g": "▄",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELICOPTER"
  },
  {
    "id": "TileHeloNose",
    "g": "▷",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 40,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELICOPTER"
  },
  {
    "id": "TileHeloRotor",
    "g": "+",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELO_ROTOR"
  },
  {
    "id": "TileHeloRotorSides",
    "g": "-",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELO_ROTOR"
  },
  {
    "id": "TileHeloBodyBack",
    "g": "█",
    "c": "#3c4655",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELICOPTER"
  },
  {
    "id": "TileHeloRotorBack",
    "g": "x",
    "c": "#b4b4b4",
    "pa": true,
    "op": false,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_HELO_ROTOR"
  },
  {
    "id": "TileHeloWindow",
    "g": "◣",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WINDOW"
  },
  {
    "id": "TileTractorCab",
    "g": "◣",
    "c": "#82c8e6",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_TRACTOR"
  },
  {
    "id": "TileTractorBody",
    "g": "█",
    "c": "#b43c28",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 30,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_TRACTOR"
  },
  {
    "id": "TileTruck",
    "g": "▄",
    "c": "#5a6e46",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 80,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_TRUCK"
  },
  {
    "id": "TileWheel",
    "g": "º",
    "c": "#787878",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WHEEL"
  },
  {
    "id": "TileWheelSmall",
    "g": "o",
    "c": "#3c3c3c",
    "pa": false,
    "op": false,
    "de": true,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_WHEEL"
  },
  {
    "id": "TileCrawlerLeft",
    "g": "◢",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CRAWLER"
  },
  {
    "id": "TileCrawlerMid",
    "g": "█",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CRAWLER"
  },
  {
    "id": "TileCrawlerRight",
    "g": "◣",
    "c": "#8246be",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 50,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CRAWLER"
  },
  {
    "id": "TileCrawlerLeg",
    "g": "^",
    "c": "#6432a0",
    "pa": false,
    "op": true,
    "de": true,
    "cv": 20,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 4,
    "nm": "TILE_CRAWLER_LEG"
  },
  {
    "id": "TileWater",
    "g": "≈",
    "c": "#2850c8",
    "pa": false,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_WATER"
  },
  {
    "id": "TileMarsh",
    "g": "≋",
    "c": "#3c6446",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 6,
    "nm": "TILE_MARSH"
  },
  {
    "id": "TileSwampWater",
    "g": "≋",
    "c": "#326450",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 5,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 8,
    "nm": "TILE_SWAMP_WATER"
  },
  {
    "id": "TileIce",
    "g": "≈",
    "c": "#b4dceb",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 0,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 5,
    "nm": "TILE_ICE"
  },
  {
    "id": "TilePier",
    "g": "═",
    "c": "#8c643c",
    "pa": true,
    "op": false,
    "de": false,
    "cv": 10,
    "fl": false,
    "ex": 0,
    "no": false,
    "mv": 3,
    "nm": "TILE_PIER"
  }
];
